### ISSUE TITLE
Consider not using defer in MemoryCache.

### ISSUE THREAD

**Issue by shurcooL** [gregjones/httpcache#36]
The `defer` keyword is certainly useful in many situations. It lets you not worry about potentially adding an early return and missing some cleanup; it also triggers even on a panic.

However, it is "relatively" expensive, and it might be worth it to avoid it in smaller snippets where it is possible to rewrite without using `defer` and the performance improvement is helpful. Consider this little comparison:

```Go
type counter struct {
	mu sync.Mutex
	i  uint64
}

func (c *counter) incrementUseDefer() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.i++
}

func (c *counter) incrementNoDefer() {
	c.mu.Lock()
	c.i++
	c.mu.Unlock()
}

func BenchmarkUseDefer(b *testing.B) {
	c := &counter{}
	for i := 0; i < b.N; i++ {
		c.incrementUseDefer()
	}
}

func BenchmarkNoDefer(b *testing.B) {
	c := &counter{}
	for i := 0; i < b.N; i++ {
		c.incrementNoDefer()
	}
}

// Output:
// BenchmarkUseDefer-8	20000000	       111 ns/op
// BenchmarkNoDefer-8 	50000000	        21.8 ns/op
```

I don't see any benchmarks in this repo so I can't know how much real world difference it'd make, but the 3 methods that `MemoryCache` has all look like good candidates to re-writing without `defer`:

```Go
// Get returns the []byte representation of the response and true if present, false if not
func (c *MemoryCache) Get(key string) (resp []byte, ok bool) {
	c.mu.RLock()
	defer c.mu.RUnlock()
	resp, ok = c.items[key]
	return resp, ok
}

// Set saves response resp to the cache with key
func (c *MemoryCache) Set(key string, resp []byte) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.items[key] = resp
}

// Delete removes key from the cache
func (c *MemoryCache) Delete(key string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	delete(c.items, key)
}
```

What do you think?

This issue is about "considering" this idea. If you've already considered it and decided it's not worth doing, feel free to tell me and close this.

If it's helpful, I can easily make a PR.

**Comment by willnorris** [comment]
I'm certainly not a decider here, but just a user of this library, but this certainly sounds good to me.  Thanks for providing the simple benchmark, @shurcooL!

**Comment by gregjones** [comment]
I don't have a problem with this change - it seems like compared to the time for an HTTP request it makes a tiny difference, but at the same time it doesn't add any complexity, so sure :+1:

**Comment by shurcooL** [comment]
Are you going to do it yourself or do you want me to make a PR?

**Comment by shurcooL** [comment]
Should I make a PR, @gregjones? It's pretty trivial. Here, I've just made #37.

**Comment by shurcooL** [comment]
Btw, I found a blog post that talks about performance considerations of `defer`, for reference:

http://lk4d4.darth.io/posts/defer/
