### ISSUE TITLE
Tests are failing.

### ISSUE THREAD

**Issue by shurcooL** [gregjones/httpcache#38]
I'm using `go version go1.6 darwin/amd64`.

The tests in this package are currently failing:

```
$ go test -v github.com/gregjones/httpcache
=== RUN   Test

----------------------------------------------------------------------
FAIL: httpcache_test.go:564: S.TestStaleIfErrorRequest

httpcache_test.go:590:
    c.Assert(err, Equals, nil)
... obtained *errors.errorString = &errors.errorString{s:"some error"} ("some error")
... expected = nil


----------------------------------------------------------------------
FAIL: httpcache_test.go:594: S.TestStaleIfErrorRequestLifetime

httpcache_test.go:620:
    c.Assert(err, Equals, nil)
... obtained *errors.errorString = &errors.errorString{s:"some error"} ("some error")
... expected = nil


----------------------------------------------------------------------
FAIL: httpcache_test.go:636: S.TestStaleIfErrorResponse

httpcache_test.go:661:
    c.Assert(err, Equals, nil)
... obtained *errors.errorString = &errors.errorString{s:"some error"} ("some error")
... expected = nil


----------------------------------------------------------------------
FAIL: httpcache_test.go:665: S.TestStaleIfErrorResponseLifetime

httpcache_test.go:690:
    c.Assert(err, Equals, nil)
... obtained *errors.errorString = &errors.errorString{s:"some error"} ("some error")
... expected = nil

OOPS: 24 passed, 4 FAILED
--- FAIL: Test (0.01s)
FAIL
exit status 1
FAIL	github.com/gregjones/httpcache	0.023s
```

**Comment by shurcooL** [comment]
It would be helpful to add CI and a badge to this repository to help catch and prevent this in the future. It also makes creating PRs easier. You can use Travis, it's free.

You can see one of my Go repos, like [this one](https://github.com/shurcooL/htmlg), as an example of how to do this. See the `.travis.yml` config file (which you can use as a template) and the badge in `README.md`.

**Comment by gregjones** [comment]
Interesting. Responses now need valid statuses, so the ones being created for the mocks in those tests are invalid. Attaching Status and StatusCode to them seems to fix things ... will be at least tomorrow before I can sort things properly though :/

**Comment by shurcooL** [comment]
> will be at least tomorrow before I can sort things properly though :/

That's okay with me. Thanks for looking into it!
