### ISSUE TITLE
Proposal: Use standard library in tests, refactor to not use gopkg.in/check.v1 package.

### ISSUE THREAD

**Issue by shurcooL** [gregjones/httpcache#41]
I think using standard library and writing tests using idiomatic basic if statements is a better approach. More people are familiar with it, and find it more readable compared to using the gopkg.in/check.v1 package.  It's easier to write because it doesn't require learning what gopkg.in/check.v1 or some other equivalent custom package has. It's what the standard library does. The added verbosity is not significant enough to offset the benefits.

For me personally, it's simpler and more consistent with all other idiomatic Go packages' code and tests.

For additional background motivation, @bmizerany gave a talk at dotGo 2014 that covered some more motivation to use standard tools for tests rather than custom external helper packages, see https://www.reddit.com/r/golang/comments/2lm3ex/dotgo_2014_blake_mizerany_three_fallacies_of/.

> Fallacy 1: Go is doing it wrong.
> 
> In reality, Go is doing things Go’s way.
>
> When Blake started out with Go, he was most familiar with Ruby, and he wrote bmizerany/assert, which was essentially trying to write Go as you would Ruby. He initially tried to make Go do things in Ruby’s way. Lesson learned. He now just uses an if-statement and t.Errorf.

(Excerpt of liveblog post from [here](http://dotgo.sourcegraph.com/post/99644344808/blake-mizerany-early-go-mistakes-dependency).)

We already have this change done in the sourcegraph/httpcache fork (see [sourcegraph/httpcache#3](https://github.com/sourcegraph/httpcache/pull/3/files)), but if you're willing to take it, I'd love to contribute it upstream.

@gregjones, what do you think of this proposal?

**Comment by shurcooL** [comment]
@gregjones, do you have any feedback on this proposal? If you're in agreement, I'd like to be able to move forward on this, and I have some additional enhancements I'd like to get reviewed and merged here afterwards (since this library appears to be the canonical Go package for client-side HTTP caching, I want it to have all possible improvements).

**Comment by gregjones** [comment]
Looks like a sensible idea, and improvements are definitely welcome... I don't have huge amounts of time at the moment to do stuff, but I'll try not to get in the way.

From just a quick look commits against your version look ok, but the fail-strings in that change could do with a little polish/consistency I think, and is there a reason `setup` isn't called from TestMain?

**Comment by shurcooL** [comment]
Awesome, great to hear.

> From just a quick look commits against your version look ok, but the fail-strings in that change could do with a little polish/consistency I think, and is there a reason `setup` isn't called from TestMain?

I haven't looked into the more subtle parts of the implementation, but I'll be sure to review it from my end before sending the PR. I'll give an answer to this question as soon as I have it.

Thanks!

**Comment by shurcooL** [comment]
> is there a reason `setup` isn't called from TestMain?

Ok, I've looked into this.

Are you suggesting that `setup` could be called once in `TestMain` for all tests to reuse, rather than each test calling `setup` and `teardown` at the end?

Is that what the current testing code does (I'm not very familiar with `gopkg.in/check.v1` and how often it calls `SetUpSuite`)? It looks like it, but I want to confirm. I think it was changed because it was unclear what the original code did, and going with setup/teardown per test is easier, gives more confidence, but possibly slower and more wasteful.

Given that these tests complete in a matter of a few seconds, there's not going to be a huge win. But I can change it to setup/teardown just once in `TestMain`.

**Comment by shurcooL** [comment]
Ok, I've confirmed, it currently only does `SetUpSuite` and `TearDownSuite` once for all tests, but calls `TearDownTest` after each individual test.

I'll change our implementation to follow suit. I think the change was an oversight and not intentional. Thanks for catching it!

**Comment by shurcooL** [comment]
> From just a quick look commits against your version look ok, but the fail-strings in that change could do with a little polish/consistency I think, and is there a reason `setup` isn't called from TestMain?

Ok, I've addressed those issues and submitted a PR #44. Please take a look.
