### ISSUE TITLE
Add two new cache backends to README

### ISSUE THREAD

**Issue by aaron42net** [gregjones/httpcache#43]
I needed a size-limited local httpcache.Cache for a project I'm working on, so I wrote [LruCache](https://github.com/die-net/lrucache) which is an in-memory LRU that can limit its total RAM usage including a guess at overhead and can optionally limit how long it will cache a given entry.

I also realized that LruCache could be used as fast cache in front of s3cache pretty easily, so I wrote [TwoTier](https://github.com/die-net/lrucache/tree/master/twotier) to allow you to use any two httpcache.Caches together.  The interface is too simple to have strong cache coherency, but it might be useful in scenarios where you don't expect the contents to change often.

They haven't been used heavily in production yet, but both have near 100% test coverage including under the race detector.

Someone else might find them useful.  Would you mind linking them in the README?

**Comment by shurcooL** [comment]
Linking to them in README sounds like a good idea to me.
