### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by fbjork** [gregjones/httpcache#54]
Any plans on adding Redis support?

**Comment by shurcooL** [comment]
I'm not aware of a Redis backend (see https://github.com/gregjones/httpcache#cache-backends), or anyone currently working on one, or planning to make one.

But it should be easy for someone to create one, and we can include it in the README.

**Comment by fbjork** [comment]
@shurcooL https://github.com/gregjones/httpcache/pull/55 :)
