### ISSUE TITLE
Can we get a in memory simple example for Go Newbie's

### ISSUE THREAD

**Issue by bwghughes** [gregjones/httpcache#57]
Would be really useful to know what how to get started with a simple in memory cache for those who aren't full-time gophers.

Good examples in README's are:

https://github.com/gin-gonic/gin/blob/develop/README.md

I'll have a go now (I'm a Golang newbie) and submit a README PR :)

**Comment by bwghughes** [comment]
I'm a bonehead.

**Comment by shurcooL** [comment]
It sounds like you found it. For posterity (in case others run into this issue), there is already a simple in-memory cache implementation in `httpcache.go`, it's called `*MemoryCache`.

The README mentions it as the first entry:

> The built-in 'memory' cache stores responses in an in-memory map.
