### ISSUE TITLE
Memory leak in setModReq

### ISSUE THREAD

**Issue by Kegsay** [gregjones/httpcache#62]
Version: `master/413781778738c08fdbb98e1dd65f5abffe8832d0`

I noticed that my Go process was consuming more and more memory over time, even though I had an LRU cache set up capped on # bytes. I traced it down using pprof to this library. It appeared that it was holding onto `http.Request` objects created from [cloneRequest](https://github.com/gregjones/httpcache/blob/413781778738c08fdbb98e1dd65f5abffe8832d0/httpcache.go#L539). These requests are being stored in a map, and superficially it looks like the library was clearing them out correctly when the request was over (response read or error occurred), so I spun up gdb:

```
$ gdb -p 11322
(gdb) break httpcache.go:165
Breakpoint 1 at 0x76040c: file /..../vendor/src/github.com/gregjones/httpcache/httpcache.go, line 165.
(gdb) continue

Continuing.
[Switching to Thread 0x7f6cd1ffb700 (LWP 11337)]

Breakpoint 1, github.com/gregjones/httpcache.(*Transport).setModReq (t=0xc420164910, orig=0xc42001b770, mod=0xc42001b860)
165		if mod == nil {

(gdb) print t.modReq
$5 = map[*net/http.Request]*net/http.Request = {
  [0xc4209de1e0] = 0xc42001af00,
  [0xc4203240f0] = 0xc4203241e0,
  [0xc4209de780] = 0xc4209de870,
  [0xc4209de5a0] = 0xc4209de690,
  [0xc42001b770] = 0xc42001b860, 
  [0xc4203250e0] = 0xc4203251d0,
  [0xc42001bc20] = 0xc42001bd10,
  [0xc420324f00] = 0xc420324ff0,
  [0xc4203242d0] = 0xc4203243c0,
  [0xc42001a690] = 0xc42001a780,
  [0xc420325950] = 0xc420325a40}

(gdb) step
166			delete(t.modReq, orig)

(gdb) print orig
$6 = (struct net/http.Request *) 0xc420325a40
```

Notice the problem? `orig` is not a valid **key** in the `map`, it's a **value**. This happens because of [this line](https://github.com/gregjones/httpcache/blob/413781778738c08fdbb98e1dd65f5abffe8832d0/httpcache.go#L228) which is then being passed to `setModReq` [here](https://github.com/gregjones/httpcache/blob/413781778738c08fdbb98e1dd65f5abffe8832d0/httpcache.go#L232) and [here](https://github.com/gregjones/httpcache/blob/413781778738c08fdbb98e1dd65f5abffe8832d0/httpcache.go#L238) which are now referencing `req2`, NOT `req`.

This means that `t.setModReq(req, nil)` is completely broken and will never delete any `http.Requests`, leaking them forever.

**Comment by shurcooL** [comment]
This is at least partially related to #61. `CancelRequest` is deprecated, and we can remove it altogether in favor of canceling requests via context. It's possible that would allow resolving this issue by removing the affected machinery.

**Comment by Kegsay** [comment]
Any idea on how soon that will happen? Given I don't cancel requests, I'd rather it was removed altogether so I don't leak quite so much. Otherwise, I'm going to have to find an alternative library to use sadly until this gets resolved. If we're removing `CancelRequest`, it'll be a breaking change no matter when we end up removing the code.

**Comment by shurcooL** [comment]
I'm sure it's possible to resolve this bug before #61. I just wanted to mention that issue because it's related.

**Comment by Kegsay** [comment]
I can confirm that the PR has fixed this issue for us. Thank you! ⭐️
