### ISSUE TITLE
Override max-age sent by server?

### ISSUE THREAD

**Issue by queirozfcom** [gregjones/httpcache#65]
Hi.

I noticed that whatever value the server sends in a `max-age` header overrides the MaxAge setting we initialize the cache with.

Is there any configuration I can use to have **my** MaxAge setting have the upper hand over whatever the server sends in a `max-age` header?

**Comment by gregjones** [comment]
Hi! Can you explain what you mean by "the MaxAge setting we initialize the cache with"?

If you include a value for `max-stale` in your request's `cache-control` header, then a response will be served from cache even when it has exceeded `max-age` (up to the value of `max-stale`). [The tests](https://github.com/gregjones/httpcache/blob/d02018f006d98f58512bf3adfc171d88d17626df/httpcache_test.go#L937) should demonstrate how this works.

**Comment by queirozfcom** [comment]
Yeah.. My bad. I didn't know about that specific parameter. Thank you for the information.
