### ISSUE TITLE
Changing status code of cached responses

### ISSUE THREAD

**Issue by victorges** [gregjones/httpcache#74]
After a while dealing with a really weird bug in our infra in which some services apparently returned a 200 response with an error body (which actually looked empty after parsing to our successful response types), I finally managed to reproduce it consistently and upon further investigation I found this code that replaces the status code of cached responses before returning them.

As I don't know why this was originally there (and it seems a pretty old change), I preferred not to send a PR right away and leave for someone with more context in the code to investigate. Couldn't find any RFCs specifying that non-OK responses should not be cached, but [this document](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#Targets_of_caching_operations) from Mozilla does imply even error responses are valid for caching (which was our case).

Would be really glad to see this fixed :)

https://github.com/gregjones/httpcache/blob/787624de3eb7bd915c329cba748687a3b22666a6/httpcache.go#L193

**Comment by shurcooL** [comment]
This might be related to https://github.com/gregjones/httpcache/pull/45.
