### ISSUE TITLE
Flag field in the Transport struct not to cache blank responses

### ISSUE THREAD

**Issue by acim** [gregjones/httpcache#96]
We have an issue with Cloudflare CDN that we sometimes receive zero-length response even though in the next request we may get correct content. The problem is that this zero-length response get cached and we start showing it on our page as well. By introducing additional bool field in the Transport struct (like SkipZeroResponse), we may use it later in RoundTrip method before cache.Set() to find out if Content-Length is zero and then skip storing to cache. I am willing to submit PR for this. So this would be just an optional behaviour.

**Comment by gregjones** [comment]
I think you could fix your problem with a separate roundtripper that deals with this weird situation - detect the zero-length, and add a header that prevents caching before it is processed by this one. So I don't think adding a flag makes sense in this library.

**Comment by acim** [comment]
OK, thank you.
