### ISSUE TITLE
Provide a basic example

### ISSUE THREAD

**Issue by fewstera** [gregjones/httpcache#97]
Hi 👋 ,

Thank you for this package.

Unless I missed it, I don't think there is a basic example of how to use this package in either the README.md or godocs.

I ended up having to read the test file to figure out how to set this up.

It would be great if you could add a quick getting started example to README.md and an [example to the godocs](https://blog.golang.org/examples). The example could be something simple like just making a GET request.

Thank you

Aidan

**Comment by acpower7** [comment]
+1

surprised there were zero examples as well

**Comment by RC1140** [comment]
See "Go Web Scraping Quick Start Guide" , its not a free book but has an example
